server:
  port: 7073

spring:
  application:
    name: contact-server

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7071/.well-known/jwks.json"

# &serverTimezone=UTC
  datasource:
    url: jdbc:mysql://localhost:3306/olive?createDatabaseIfNotExist=true&useLegacyDatetimeCode=false
    username: root
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always


  jpa:
    hibernate:
#      properties:
#        jdbc:
#          time_zone: UTC        
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect    
      
logging:
  file:
    name: ./logs/contact-server.log
