server:
  port: 7071

eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:7074/eureka/

spring:
  application:
    name: olive-auth-server

  datasource:
    url: jdbc:mysql://localhost:3306/oliveFoundation?createDatabaseIfNotExist=true
    username: root
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect


logging:
  file:
    name: ./logs/olive-auth-server.log
